### ISSUE TITLE
will you please provide some install description?

### ISSUE THREAD

**Issue by deepkenlau** [p12tic/libsimdpp#121]
On centos, i use these command to install the lib.
cd libsimdpp-master
mkdir build 
cd build
cmake ../
sudo make install.

After that, i want to compile a simple cpp file(print hello world) and include simd.h. But all i got was errors.
[output.log](https://github.com/p12tic/libsimdpp/files/1977724/output.log)

Would you please help me with that? thank you.

**Comment by sahmad98** [comment]
This is a header only library, so their is nothing to compile and build.
You have not provided the __Instruction Set__ for which to compile your code. It should be something like
```
g++ -o test test.cpp  -I/usr/local/include/libsimdpp-2.1 -DSIMDPP_ARCH_X86_SSE4_1 -msse4
```
Read [this](http://p12tic.github.io/libsimdpp/v2.2-dev/libsimdpp/w/arch/selection.html) for suitable Instruction Set selection.
