### ISSUE TITLE
How to Use This Library?

### ISSUE THREAD

**Issue by ardianumam** [p12tic/libsimdpp#155]
Hi,

I'm new in this SIMD thing. From what I search in the internet here and there, using this library can be done by just including the header (without any build/cmake, etc). In by case, when I compile [this example](https://github.com/p12tic/libsimdpp/blob/2e5c0464a8069310d7eb3048e1afa0e96e08f344/examples/vector-add.cpp) by ```gcc -o my_app vector-add.cpp```, I got this error: ```fatal error: simdpp/simd.h: No such file or directory```. This is my gcc version: ```gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0```.

Could you please provide the "hello word" tutorial how to use this libary? Thanks a lot.

**Comment by GabrieleGiuseppini** [comment]
You probably want to tell gcc where to find the include files, i.e. the location of your `simdpp` directory. Have a look at https://www.rapidtables.com/code/linux/gcc/gcc-i.html.

**Comment by ardianumam** [comment]
Solved, many thank @GabrieleGiuseppini .
