### ISSUE TITLE
loading integers

### ISSUE THREAD

**Issue by michalfapso** [p12tic/libsimdpp#23]
Hi Povilas,

this is just a minor issue. The load() function seems to work only with vectors of unsigned ints and floats. Signed ints seem to be not supported:
``` cpp
int vi[16];
int32x4 i;
i = load(&vi[0]); // OK
i = load<uint32x4>(&vi[0]); // OK
i = load<int32x4>(&vi[0]); // compilation FAILS

i = 10 + load<int32x4>(&vi[0]) * 2; // compilation FAILS - real use case
```
...the last line shows just why I would like to use the explicit template argument for the load function. Although it works with uint32x4, It would be nice to be able to use the same type as for the target "i" variable. But as I said, this is a very low priority thing :o)

Cheers,
Michal

**Comment by p12tic** [comment]
This has been fixed recently.
