### ISSUE TITLE
test_zero() and test_ones() for longer than 128bit vectors

### ISSUE THREAD

**Issue by michalfapso** [p12tic/libsimdpp#24]
Hi Povilas,

sorry for my recent splash of messages :o) I started to work more intensely on vectorizing some scalar code.

When I have a mask vector, I sometimes need to know whether all values in the vector are true or false. I have to use a bit_cast to convert the mask to uint vector like this:

``` cpp
mask_int32x8 mask = ...
bool all_true = simdpp::sse::test_ones(simdpp::bit_cast<uint32x8>(mask));
```
which is not a problem, but the test_zero() and test_ones() in simdpp/sse/compare.h are implemented only for 128bit vectors. I don't know if it would be ok to add the support for 256bit vectors to the same header file, since such long vectors are supported by avx, not sse.

``` cpp
namespace simdpp {
namespace SIMDPP_ARCH_NAMESPACE {
namespace sse {

template<class = void> SIMDPP_INL
bool test_ones(const uint32x8& a)
{
	uint32x4 v1, v2;
	simdpp::split(a, v1, v2);
	return
		test_ones(uint8x16(v1)) &&
		test_ones(uint8x16(v2));
}

template<class = void> SIMDPP_INL
bool test_zero(const uint32x8& a)
{
	uint32x4 v1, v2;
	simdpp::split(a, v1, v2);
	return
		test_zero(uint8x16(v1)) &&
		test_zero(uint8x16(v2));
}

// variants for uint16x16, uint8x32, uint64x8 should follow

}}}
```

Cheers,
Michal

**Comment by p12tic** [comment]
A generic `test_bits_any` has been added.
