### ISSUE TITLE
vmaxq_f64 in float64x2 detail::insn::i_min

### ISSUE THREAD

**Issue by jacksonmj** [p12tic/libsimdpp#26]
This seems wrong, it should probably be vminq_f64.

https://github.com/p12tic/libsimdpp/blob/39354c3e65b93ebdf26d1d954dcf57b8249e1c33/simdpp/detail/insn/f_min.h#L68

**Comment by p12tic** [comment]
Indeed, thanks' for noticing.

**Comment by p12tic** [comment]
Fixed in 3e5950c80dbbd97f7314476450fb0f01a33dcb26.
