### ISSUE TITLE
General question about simdpp vector types

### ISSUE THREAD

**Issue by kforner** [p12tic/libsimdpp#29]
Hi,
From what I think I understood, in order to use the simdpp optimized functions, you must use the libsimdpp vector types.
So suppose I already have two float arrays, if I want to add them using libsimdpp, I have to create two vectors and copy the arrays in the vectors, is it right ? 
Meaning that you cannot directly use the functions on stl vectors for instance ?

Thanks

**Comment by p12tic** [comment]
Hi,

You will need to load the data into the SIMD vectors, do the operations and store the data to the stl vector. This copying is not overhead -- one will need to load data to and from SIMD registers regardless of what API one uses -- be it intrinsics, assembler or libsimdpp.

For example, to add data in two arrays:

`void add_arrays(const float* a, const float* b, float* c, unsigned size)
{
    // assuming a, b and c are correctly aligned and that size is a multiple of N
    using namespace simdpp;
    const unsigned N = 4; // one might want to set this to 8 on AVX
    for (int i = 0; i < size/N; ++i) {
        float<N> ia = load(a); a+=N;
        float<N> ib = load(b); b+=N;
        ia = add(ia, ib);
        store(c, ia); c+=N;
    }
}`

The above is the simplified example. In real world you will want to handle misalignment and any `size`, not only a multiple of N. I guess I'll add a real-world example to the repository.

**Comment by kforner** [comment]
Ah ok, thanks. The vector types are used to represent the quaternions of floats for example. 
I thought there were STL-like vectors that you had to use to be able to use your simd-optimized functions. 
It makes more sense.
