### ISSUE TITLE
Documentation doesn't build: no doc.radis.lt/libsimdpp

### ISSUE THREAD

**Issue by migdalskiy** [p12tic/libsimdpp#30]
When trying to build documentation, wget... http://doc.radix.lt/libsimdpp/ fails because that directory doesn't exist.

**Comment by p12tic** [comment]
Hi, for the moment the actual doc generator is not exposed. It's based on a wiki similar to what's used in cppreference.com, thus it needs to be properly secured and transferred to proper hosting provider before it can be made public.

A static copy of the docs is available here http://p12tic.github.io/libsimdpp/v2.0~rc2/libsimdpp/, this should suffice for most purposes.
