### ISSUE TITLE
workaround: _mm_set_epi64x identifier not found

### ISSUE THREAD

**Issue by henningpeters** [p12tic/libsimdpp#33]
I am building a Python extension that uses libsimdpp. As I want to provide compatibility with Python 2.7 (yep, it's still pretty popular) I need to compile against VS 2008 (using the cxx98 branch). There, I am getting following error when compiling with SSE2 options enabled:

```
error C3861: '_mm_set_epi64x': identifier not found
```

According to https://msdn.microsoft.com/en-us/library/dk2sdw0h(v=vs.90).aspx the correct header file is `intrin.h` and just [adding it](https://github.com/spacy-io/sense2vec/commit/1d94617e324dc635dcf95bb2d793d8358d64a405) makes it indeed work.

Newer VS versions don't have that problem. Have you heard about this before? Why does libsimdpp not include `intrin.h`? Does my workaround look ok?

Full logs: https://ci.spacy.io/builders/sense2vec-win64-py27-64-install/builds/47/steps/shell_2/logs/stdio
Workaround: https://github.com/spacy-io/sense2vec/commit/1d94617e324dc635dcf95bb2d793d8358d64a405

**Comment by p12tic** [comment]
It's simply that libsimdpp was not tested with VS 2008. Could you please prepare a PR with the workaround you mentioned?

**Comment by henningpeters** [comment]
How do you keep the cxx98 branch in sync? Is this an automatic process (master -> cxx98 branch?) or do you need a PR only for the cxx98 branch (VS 2008 obviously doesn't compile the cxx11 branch)?

**Comment by p12tic** [comment]
Yes, I need a PR to the cxx98 branch.

**Comment by p12tic** [comment]
Fix merged.
