### ISSUE TITLE
How to call functions with partial platform support

### ISSUE THREAD

**Issue by henningpeters** [p12tic/libsimdpp#34]
Maybe I haven't fully understood expressions yet, but how do you envision calling functions that only have partial architecture support, e.g., https://github.com/p12tic/libsimdpp/blob/master/simdpp/detail/expr/f_fmadd.h#L024. It seems counterintuitive to add checks for platform support in application code again.

Wouldn't it make sense to add a generic implementation as fallback in case no specific instruction set is available?

**Comment by p12tic** [comment]
It's not possible to perform certain operations in an efficient way without hardware support. For example, see how the fma for double arguments is implemented in C: https://github.com/andikleen/glibc/blob/b0399147730d478ae45160051a8a0f00f91ef965/sysdeps/ieee754/dbl-64/s_fma.c.

Therefore, it's very likely that for architectures that lack support of needed operations, the programmer will need to use a different algorithm altogether if he needs to achieve acceptable performance.

On the other hand, in this particular case fmadd for floats can be implemented efficiently via mul+add operations in doubles, so this is indeed missing functionality in libsimdpp.

Do you know any other functions without efficient fallback path when one is possible?

**Comment by p12tic** [comment]
In short, it's impossible to efficiently compute fmadd/fmsub without hardware support. Any code relying on these functions can't be efficiently implemented on target platform at all, so a different algorithm must be used or a sacrifice on precision must be made. Working around lack of fused-multiply-add support makes little sense.
