### ISSUE TITLE
failed to load a vector of double.

### ISSUE THREAD

**Issue by soga-denken** [p12tic/libsimdpp#42]
I tried to load a vector of double into float64<2,void> but it encountered a segmentation error.

OS: Windows 10 64bit
platform: Visual Studio 2015 with 32 bits debug mode

```
#define  SIMDPP_ARCH_X86_AVX2

//float vec[2]; // this works
double vec[2]; // this results in seg. error.

vec[0] = 0;
vec[1] = 1;

float64<2, void> vec64_4 = load(&vec[0]);
```

**Comment by p12tic** [comment]
The issue is likely is that `vec` is not aligned on 16-byte boundary and `load` can only perform aligned loads. Try either `load_u` or `SIMDPP_ALIGN(16) double vec[2];`.

**Comment by soga-denken** [comment]
ah, I forgot about alignment... 

Thank you for your help!
