### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by soga-denken** [p12tic/libsimdpp#44]
Hi. I tried to write a simple example for libsimdpp.
I thought the following code should run, but it returned an run time error at load(a).

Do you have any idea?

```
#define  SIMDPP_ARCH_X86_AVX2
#include<simdpp/simd.h>
int main()
{
	const int N = 8;

	// should be aligned to  __mm256
	float SIMDPP_ALIGN(32) a[N];

	for (int i = 0; i < N; ++i)
	{
		a[i] = i;
	}
        // this works.
        //simdpp::float32<4, void> a_avx = simdpp::load(&a[0]);
	simdpp::float32<8, void> a_avx = simdpp::load(&a[0]);

	return 0;
}
```

**Comment by p12tic** [comment]
Which compiler and OS are you using and what exactly error are you getting? Also, could you please verify that your CPU both supports AVX2 and that this is enabled by the OS? In particular, certain virtual machines don't have support for certain instruction sets even when hardware has them which results in invalid instruction errors.

**Comment by soga-denken** [comment]
Yes, you are correct. My new CPU did not support AVX2... ouch.

I will consider dynamic dispatch!
