### ISSUE TITLE
What alternatives to libsimdpp are there?

### ISSUE THREAD

**Issue by eriksjolund** [p12tic/libsimdpp#57]
To understand the pros and cons of a software library, it can be good to compare it to the
alternatives that exist.

I found for instance this:
https://github.com/VcDevel/Vc

If anyone has compared libsimdpp to other SIMD wrapper template libraries (C++), I would be interested to hear your opinion.

**Comment by p12tic** [comment]
I haven't seen a extensive comparison of SIMD wrappers anywhere. This [page at libvolk](http://libvolk.org/comparisons.html) is pretty good list of libraries, though you've probably already seen it and it's perhaps not exactly what you're looking for.

To my knowledge there's no other open-source SIMD wrappers that provide as extensive instruction set coverage as libsimdpp. For example, no library known to me supports either of AVX512F, VMX/VSX or MSA instruction sets. Of course, this might be biased opinion, please correct me if this looks wrong.
