### ISSUE TITLE
Feature request: Add support for AVX512BW

### ISSUE THREAD

**Issue by eriksjolund** [p12tic/libsimdpp#58]
As mentioned in [Intel® Xeon® Processor Scalable Family Technical Overview](https://software.intel.com/en-us/articles/intel-xeon-processor-scalable-family-technical-overview) 
the platform Purley will come with support for [AVX512BW](https://en.wikipedia.org/wiki/AVX-512). I believe CPUs will be released autumn 2017 (or maybe later). 

By looking at
http://p12tic.github.io/libsimdpp/v2.0~rc2/libsimdpp/arch/selection.html
it seems AVX512BW is not supported by libsimdpp right now.

AVX512BW will provide 8-bit and 16-bit integer operations that could speed things up.

As a feature request:
It would nice if libsimdpp could support AVX512BW.

**Comment by p12tic** [comment]
AVX512BW support is already being implemented in a private branch.

**Comment by p12tic** [comment]
AVX512BW support added in e673cca7e5193dda4c8a3c374139d782e60e4ded.
