### ISSUE TITLE
What examples are there of open source software that uses libsimdpp? 

### ISSUE THREAD

**Issue by eriksjolund** [p12tic/libsimdpp#59]
Of course I could also use Google or GitHub advanced search to search for examples.
When I search for _"<simdpp/simd.h>"_ in GitHub advanced search, I get
the [result](https://github.com/search?utf8=%E2%9C%93&q=%22%3Csimdpp%2Fsimd.h%3E%22&type=Code).

Maybe we should create a list in the wiki
https://github.com/p12tic/libsimdpp/wiki
?

**Comment by danking** [comment]
The [Hail project](https://github.com/hail-is/hail) uses libsimdpp.

**Comment by p12tic** [comment]
Added a new section to the wiki. Feel free to add new entries there. Thanks!
