### ISSUE TITLE
type mistakenly induced

### ISSUE THREAD

**Issue by hanzz2007** [p12tic/libsimdpp#60]
hi, this snippet of code could not be compiled in vs2017, for out_vec was mistakenly induced as uint32x8
`void prelu_simdpp(const T* const in_data, const int len, const float coeff, T* const out_data)
{
	const int len_aligned = len & (-8);

	for (int i = 0; i < len_aligned; i += 8)
	{
		auto in_vec = simdpp::load_u<simdpp::int32x8>(in_data + i);
		auto mask_vec = simdpp::cmp_gt(in_vec, 0);
		auto out_vec = simdpp::blend(in_vec, in_vec * coeff, mask_vec);
		auto out_vec2 = to_float32(out_vec);
	}
}
`

**Comment by p12tic** [comment]
Hi, thanks for the bug report.

It looks like the problem here is that the return type of multiplication operator (in `in_vec * coeff`) is wrong, which causes `simdpp::blend` to also have wrong return type. As a workaround, `mul` function could be used.

**Comment by p12tic** [comment]
Fixed in 24966bc460f01. Thanks!
