### ISSUE TITLE
[question] How to find max/min of float32 vector of arbitrary size?

### ISSUE THREAD

**Issue by yurivict** [p12tic/libsimdpp#63]
I only see functions where size is a template in simdpp/core/f_max.h. How do I compute when size is arbitrary?

**Comment by p12tic** [comment]
The size of a single vector is always a template argument. It corresponds one or more hardware registers which of course have fixed width. The expectation is that a highest supported hardware register size is selected during compile time and then corresponding types are used to perform computations. If you want to perform max or min operation of arbitrary array, you should do something like this: 

```
void compute_max(float* p1, float* p2, float* pmax, unsigned size)
{
    // assuming size % N == 0 or that sufficient amount of extra memory is allocated
    const unsigned N = SIMDPP_FAST_FLOAT32_SIZE;
    for (unsigned i = 0; i < size; i += N) {
        float32<N> a1 = load(p1);
        float32<N> a2 = load(p2);
        float32<N> res = max(a1, a2);
        store(pmax, res);

        p1 += N;
        p2 += N;
        pmax += N;
    }
}
```

**Comment by yurivict** [comment]
This works, thanks!
