### ISSUE TITLE
SSE3 optimization of float32 reduce_add(), reduce_max(), and others not working

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#64]
given that SSE3 enabled implies SSE2 is also enabled, the sequence of #elif sections in the code:

#elif SIMDPP_USE_SSE2
    float32x4 sum2 = _mm_movehl_ps(a, a);
    float32x4 sum = add(a, sum2);
    sum = add(sum, permute2<1,0>(sum));
    return _mm_cvtss_f32(sum);
#elif SIMDPP_USE_SSE3
    float32x4 b = a;
    b = _mm_hadd_ps(b, b);
    b = _mm_hadd_ps(b, b);
    return _mm_cvtss_f32(b);

causes SSE2 code to be used even when SSE3 is available.

**Comment by p12tic** [comment]
Fixed in 731f670eecef8732e763df3193dcee7ef08670fa. Thanks!
