### ISSUE TITLE
NEON 128-bit test_bits_any() more efficient using uint64x2?

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#65]
would it be better to use uint64x2 as the 128-bit optimized implementation of i_test_bits_any() for NEON?

this generates fewer instructions:
```
SIMDPP_INL bool i_test_bits_any(const uint64<2>& a)
{
    uint64x2 r = bit_or(a, move2_l<1>(a));
    return extract<0>(r) != 0;
}
```
as compared to this:
```
SIMDPP_INL bool i_test_bits_any(const uint32<4>& a)
{
    uint32x4 r = bit_or(a, move4_l<2>(a));
    r = bit_or(r, move4_l<1>(r));
    return extract<0>(r) != 0;
}
```

**Comment by p12tic** [comment]
Thanks for the bug report! i_test_bits_any was written with 32-bit ARM in mind, in which case transferring a 32-bit quantity to GPR is more efficient. On 64-bit this approach is not the most optimal indeed. This was fixed in b46d4aa48e58a3840f5fd25ebccde86689fa1e98.
