### ISSUE TITLE
Linux ICC compilation flag 

### ISSUE THREAD

**Issue by wilsonCernWq** [p12tic/libsimdpp#68]
Hi

I am new to this library, so maybe I am wrong. But I noticed that in [here](https://github.com/p12tic/libsimdpp/blob/master/cmake/SimdppMultiarch.cmake#L280), the flag for ICC is `-mavx512f`. 

Shouldn't it be `-xCOMMON-AVX512` (or `-xMIX-AVX512` for Xeon Phi x200 and `-CORE-AVX512` for other Xeon Phi) according to [intel specification](https://software.intel.com/en-us/articles/compiling-for-the-intel-xeon-phi-processor-and-the-intel-avx-512-isa)? 

On my KNL, the ICC can compile the code with warnings that 
```
icpc: command line warning #10159: invalid argument for option '-m'
```
Will the program still run SIMD instructions correctly ?

Thanks

Qi

**Comment by wilsonCernWq** [comment]
I think I figured it out :D Thanks !

**Comment by p12tic** [comment]
Thanks for the bug report! If anyone else stumble on this same issue, libsimdpp indeed used an undocumented flag of ICC. Fortunately, it worked as expected. To avoid any issues in the future, cd813039e6c00dad90a0f3605401e0aeca3105a7 fixes this issue by using Intel specific flags when possible.
