### ISSUE TITLE
True/False Running cmake is not required to correctly use the header files in this library?

### ISSUE THREAD

**Issue by danking** [p12tic/libsimdpp#73]
AFAICT, there's no need for me to run cmake. I can just point my include directories at libsimdpp and get going. It seems cmake is only needed for building a distribution, right?

Thanks.

**Comment by p12tic** [comment]
Yes, that's correct. Cmake is not required to use libsimdpp. It's just used as a helper for building internal tests.

If you want to use internal dispatch functionality, you might want to include cmake/SimdppMultiarch.cmake.
