### ISSUE TITLE
uninitialized var warning in NEON variant of splat()

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#74]
simdpp::float32x4 foo1(float a)
{
	return simdpp::splat(a);
}

.../submodule/libsimdpp/simdpp/detail/insn/set_splat.h: In function ‘simdpp::arch_neonfltsp::float32x4 foo1(float)’:
.../submodule/libsimdpp/simdpp/detail/insn/set_splat.h:302:43: warning: ‘r.simdpp::arch_neonfltsp::float32<4u>::d_’ is used uninitialized in this function [-Wuninitialized]
     typename detail::remove_sign<V>::type r;

aarch64-poky-linux-g++ (GCC) 6.3.0
#define SIMDPP_ARCH_ARM_NEON_FLT_SP

**Comment by p12tic** [comment]
Thanks for the bug report. It looks the warning is wrong. Disabled it in b03d71eed805410e35ceb0d464ce3d2af7325f7e.
