### ISSUE TITLE
test_bits_any() gets compilation errors when called with an expression

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#76]
Tested with xcode 9.0, SSE4_1 target 

```
bool foo1a(uint32x4 a, uint32x4 b)
{
	return test_bits_any(bit_and(a,b));
}
```
.../submodule/libsimdpp/simdpp/core/test_bits.h:28:70: No matching constructor for initialization of 'typename detail::get_expr_nosign<uint32<4, expr_bit_and<uint32<4, uint32<4, void> >, uint32<4, uint32<4, void> > > >, typename uint32<4, expr_bit_and<uint32<4, uint32<4, void> >, uint32<4, uint32<4, void> > > >::expr_type>::type' (aka 'uint32<16U / 4, simdpp::arch_sse4p1::expr_bit_and<simdpp::arch_sse4p1::uint32<4, simdpp::arch_sse4p1::uint32<4, void> >, simdpp::arch_sse4p1::uint32<4, simdpp::arch_sse4p1::uint32<4, void> > > >')

```
bool foo1c(uint32x4 a, uint32x4 b)
{
	return test_bits_any(bit_and(a,b).eval());
}
```

this compiles successfully. the code uses an unnecessary pand instruction, presumably because of the use of eval():
```
Inspiration::foo1c(simdpp::arch_sse4p1::uint32<4u, void>, simdpp::arch_sse4p1::uint32<4u, void>):
0000000000000230	pushq	%rbp
0000000000000231	movq	%rsp, %rbp
0000000000000234	pand	%xmm1, %xmm0
0000000000000238	ptest	%xmm0, %xmm0
000000000000023d	setne	%al
0000000000000240	popq	%rbp
0000000000000241	retq
```
(pand could have been skipped in favor of the AND operation done by ptest)

I noticed this function doesn't appear in the docs. Is it not meant to be a public interface?

**Comment by p12tic** [comment]
Thanks for the bug report. The issues with `test_bits_any` have been fixed in 7ae62d1601255 and 0b09593d2ad9 and the documentation has been updated in f410830bf756b.
