### ISSUE TITLE
aarch64 splat for float32x4 looks really inefficient

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#77]
```
float32x4 foo(float a)
{
    return splat(a);
}
```
the generated code looks really terrible, at least in comparison to SSE. I guess ARMv7 can't do any better than that? Nevertheless ARMv8 can using vdupq_laneq_f32(). The NEON implementation of i_splat4() for float32x4 should probably have a SIMDPP_64_BITS variant.

**Comment by p12tic** [comment]
Thanks for the bug report! The issues with splat on ARM have been fixed in ef1b2adfccab9 and 3857ceaf27b. Just to double-check, make sure you're using SIMDPP_ARCH_ARM_NEON_FLT_SP for floating-point code on ARM.
