### ISSUE TITLE
sse2 implementation of i_to_float32(const float64<4>& a) broken (again)

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#87]
The args to 

    return _mm_movelh_ps(r2.native(), r1.native());

are backwards. the lower 2 lanes of _mm_movelh_ps's 2nd arg are moved to the upper 2 lanes of the first arg.

Should be:

    return _mm_movelh_ps(r1.native(), r2.native());

**Comment by p12tic** [comment]
Thanks for spotting this. I've merged your PR and added test to guard against regressions like this in 82bc8590df53ae6670610d1110b2a51c7d827228.
